.gitignore
=> placeholder

.vscode/launch.json, git/config.go, git/github.go, git/misc.go, git/repo.go, opp.go
This way you can go install the tool.
=> Renames main.go into opp.go

.vscode/launch.json, cmd/pr.go, git/branch.go, git/config.go, git/github.go, git/misc.go, git/repo.go, opp.go
It pushes to a new branch, creates the github pull requests.
It knows about dependent pull requests.
=> Adds a command to create a PR.

cmd/push.go, cmd/rebase.go
And their dependant PRs as well.
=> Adds a command that pulls / rebases PRs.

cmd/init.go, cmd/pr.go, cmd/push.go, cmd/rebase.go, core/github.go, core/misc.go, core/repo.go, go.mod, go.sum, opp.go
This way it's possible to mock it in tests.
=> Inject the object that calls the github API.

.vscode/launch.json, cmd/merge.go, cmd/merge_test.go, cmd/pr.go, cmd/rebase.go, core/branch.go, core/config.go, core/repo.go, core/tests/testrepo.go, opp.go
Explanation: This commit updates the PR states and repo checkout functions to include a context parameter and to clean up PRs that do not exist locally.
=> Commit message: chore: Update PR states and repo checkout

cmd/init.go
=> Guess the main branch.

cmd/init.go
Add functions to make things more explicit.
=> Refactor the init command a bit.

.vscode/launch.json, cmd/pr.go, core/repo.go
You can now choose a different ancestor than the one which is
detected automatically.
=> Makes opp pr better.

cmd/pr.go, core/repo.go
Makes the code easier to understand, rename a few variables,
adds documentation.
=> Refactor the opp pr command.

cmd/pr_test.go, core/tests/testrepo.go
=> Fixes tests in the CI.

core/tests/testrepo.go
=> Fixes tests.

cmd/merge.go
Even if it was given as an argument.
=> Checkout the main branch if merging the checkedout PR.

core/repo.go
Because it's too slow if the repo is big ...
=> Don't use go-git to push.

opp.go
Instead, complain that the user should run it.
=> Make opp init not run silently.

.github/workflows/go.yml, cmd/merge.go, cmd/pr.go, core/config.go, core/repo.go, opp.go
=> Adds timeouts for the github API usages.

cmd/init.go
=> Makes init set the core.excludesfile if unset.

cmd/clean.go, cmd/clean_test.go, core/branch.go, core/repo.go, core/tests/testrepo.go
And fixes a bug : it was not reassigning dependencies correctly.
=> Adds a test to opp clean.

cmd/init.go
=> Correct name of 'write:discussion' permission for init command

cmd/merge.go
Don't pretend it works with more than one.
=> Merge works with a single PR.

.github/CODEOWNERS
Since only collaborators in the repo can merge anyway.
=> No need for code owners.

cmd/pr.go
=> [Refactor] Make Create use a full github object.

cmd/merge.go, cmd/misc.go, cmd/pr.go
Extracts the code that parses arguments to get the pr number into
a function
=> Extracts code into a function.

cmd/merge.go
If you call `opp merge` right after someone else updated the branch
you are merging to, `opp` responds with "still being checked by
github" because github needs a few seconds to attempt to merge in the
background, to tell you if the PR is mergeable or not.
This change waits for this to happen for 30s.
=> Wait 30 seconds for github to create merge commit.

cmd/pr.go, core/repo.go
When you do `opp pr` and we need to rebase and the rebase fails,
it's better if opp checks out the commit you were on before.
=> Checkout the branch you were on if an error happens.

cmd/clean.go, go.mod
At the moment cleaning PRs is done sequentially: one PR after another.
In this PR, the process is parallelized.
=> parallelize clean

cmd/pr_story_test.go, core/story_service.go
- Linear [CUP-2](https://linear.app/cupcic/issue/CUP-2)
- the Story is added as a bullet point and shows the Tool and the actual Story
- the body is kept out from bullet points, just in case there are already bullet points in the PR body :)
=> [CUP-2] improve body format

cmd/pr.go, core/story/story_service.go, core/story/story_service_test.go
this is a preparatory task before fetching assigned stories directly for the story tool (jira / linear).
=> create story package

cmd/clean_test.go, cmd/pr_test.go, cmd/rebase_test.go, core/branch.go, core/repo.go, core/state.go, core/state_test.go, core/tests/testrepo.go
The state was managed by the LocalPR itself.
Create a class to handle it outside the PR so that
we can store state for branches too.
=> [CUP-10] Refacto how we store the state of PRs.

core/story/linear.go, core/story/story_fetcher.go
This will make it possible to use these fields in tests.
=> chore: make Story fields public

core/story/linear.go, go.mod, go.sum
This PR adds 3 retries to the Linear graphql client.
=> Add retries to the Linear graphql client
