cupcicm/opp

- core/branch.go
- core/github.go
- core/tests/testrepo.go
- opp.go
Walks back the dependency chain to the main branch.
> Create a function that returns all ancestors of a PR.

- cmd/init.go
- cmd/pr.go
- cmd/rebase.go
Also fixes a problem when you don't own the repo.
> fix: handle github repo without .git suffix in init command

- cmd/merge.go
- core/repo.go
- git fetch doesn't delete the branches that don't exist on the
remote anymore for some reason.
- git fetch -p does, but is not implemented in go-git.
> Make fetch prune the local branches.

- cmd/rebase.go
- core/repo.go
If a PR B depends on PR A and you git commit --amend a commit in PR A
then git rebase will not know anymore whether PR B should contain the
new or the old version, and a git rebase will conflict between those
two.
Use this to our advantage : try to rebase silently, and if that rebase
fails, hope that it's because of that problem and let the user check
that all the commits are actually part of PR B.
> Make rebase work a lot better with dependant changes.

- core/repo.go
So, use the output of `git status` instead.
> the WorkTree.Status() method takes too long to run.

- cmd/pr.go
- cmd/pr_test.go
- cmd/rebase.go
- core/repo.go
- core/tests/testrepo.go
Except for Checkout() that really shouldn't take long.
> Use a context in almost all git exec commands.

- cmd/push.go
When the dots are close to the URL, ctrl clicking puts them in the URL.
> Fix hyperlink.

- cmd/app.go
The script needs to be in the user's path. This allows the user to
customize opp / create new commands.
> Makes opp run `opp-xxx.sh` scripts when no command match.

- cmd/merge.go
- cmd/pr.go
- core/github.go
- core/tests/testrepo.go
- go.mod
- go.sum
Add support for draft PRs.
Note that this required upgrading to a more recent version of go-github. Although the draft functionality has been available since 2019, I took the opportunity to upgrade to the latest version.
> Add support for draft PRS

- cmd/rebase.go
- cmd/rebase_test.go
- core/repo.go
- core/tests/testrepo.go
It now tries to guess where the ancestor finishes and where the PR
starts, and rebases only the PR commits.
Notably, this should make opp work with dependent PRs with the squash
and merge strategy (but I haven't tried :P)
> Makes opp pull more clever.

- cmd/rebase.go
- cmd/rebase_test.go
- core/repo.go
- core/tests/testrepo.go
The local version could have commits we don't want in our history.
Only when it's pushed do we use the new commits in the history
of dependent branches.
> Always rebase on the distant version.

- cmd/pr.go
- core/github.go
- core/tests/testrepo.go
But don't do it the first time to make it faster.
> Avoid using issue numbers when creating PRs.

- cmd/pr.go
Handle PR-creation failure instead of blindly trying to checkout
a non-existent local PR branch.
Trace from panics that were occurring is as follows:
```
goroutine 1 [running]:
github.com/cupcicm/opp/core.(*LocalPr).LocalBranch(...)
opp/core/branch.go:197
github.com/cupcicm/opp/core.(*LocalPr).LocalName(0x140000bc000?)
opp/core/branch.go:110 +0x18
github.com/cupcicm/opp/core.(*Repo).Checkout(0x1400018f8d0?, {0x104c36410?, 0x0?})
opp/core/repo.go:171 +0x30
github.com/cupcicm/opp/cmd.PrCommand.func1(0x1400009e200)
opp/cmd/pr.go:94 +0xd0
github.com/urfave/cli/v2.(*Command).Run(0x140001f02c0, 0x1400009e200, {0x1400009c2e0, 0x2, 0x2})
go/pkg/mod/github.com/urfave/cli/v2@v2.25.7/command.go:274 +0x730
github.com/urfave/cli/v2.(*Command).Run(0x140000a4160, 0x1400009e140, {0x14000020150, 0x3, …
```
> Prevent panic when PR creation fails

- cmd/merge.go
- cmd/merge_test.go
- core/tests/testrepo.go
If you call `opp merge` right after someone else updated the branch
you are merging to, `opp` responds with "still being checked by
github" because github needs a few seconds to attempt to merge in the
background, to tell you if the PR is mergeable or not.
This change waits for this to happen for 30s.
> Wait 30 seconds for github to create merge commit.

- cmd/app.go
- cmd/comment.go
- cmd/misc.go
- core/github.go
- core/tests/testrepo.go
Add a simple `comment` sub-command which allows adding a top-level
(non-review) comment to a PR.
Based on extensive market research, it appears that there is are potential future customers of `opp` who rely on triggering CI and related workflows by adding top-level comments to a PRs.
In order to fulfill the mission of making it possible to never touch the PR UI in Github, this PR makes it possible to add (non-review) comments on PRs directly from the command line.
> Add command to add comments to PRs.

- cmd/misc.go
When merging the current branch, we need to checkout the main branch before
because deleting the branch we are currently sitting on is dangerous.
The check for "is head a PR" was not executed when running `opp merge pr/xxxx` but it's possible that you currently have  `pr/xxxx` checked out.
> Fixes a bug on `opp merge`

- cmd/pr.go
- core/config.go
- core/repo.go
When opp.keep_master_clean is set, if you create a PR, the commits
you have selected in the PR will be removed from the master branch.
This keeps the master branch clean.
> Adds a setting that allows opp to keep your master branch clean.

- cmd/pr.go
- core/config.go
I don't like it. I feel that half of my PRs I want to "extract"
them to the PR branch so that they don't pollute the branch I am
working on, but the other half I want to keep on my current branch,
because I want to continue building commits on top of them.
So I propose to make it a command line flag instead. Spent a while
debating what the right word would be but I think "extract" makes sense ?
> Remove the "keep_master_clean" setting.

- cmd/pr.go
- cmd/pr_story_in_title_test.go
- core/story_service.go
- core/tests/testrepo.go
This PR extracts the story from the commit messages and adds it to the PR title.
It is a basic first implementation:
- the story is identified based on a regexp
- if the regexp pattern is identified in the PR title, then nothing is added
- else, the regexp pattern is searched in all commits message, stopping at the first occurence.
> add story to pr title

- cmd/pr.go
- core/story_service.go
This is the first PR for a feature mentioned [here](https://github.com/cupcicm/opp/pull/160#issuecomment-2397865922), which consists in adding the link to the Story to the PR body.
Todo next: implement the `enrichBody` method.
> refactor: extract Story so that it can be used to enrich the Body

- cmd/pr.go
- core/config.go
- core/story/story_service.go
- core/tests/testrepo.go
- go.mod
The config format is now, for stories:
```
story:
tool: linear
url: https://full.base.url/issues
```
All these fields are required to make the Story features work. So: 
- if none are set: then no enrichment with Story
- if all are set: then enrichment with Story
- else: panic
In addition:
- another param can be added: `story.enrich` to disable the Body enrichment. By default it is set at true.
- opp also panics when the Story regexps don't compile
> simplify config

- cmd/app.go
- cmd/pr.go
- cmd/pr_story_test.go
- core/config.go
- core/story/story_fetcher.go
- core/story/story_service.go
- core/tests/testrepo.go
- opp.go
This PR uses the StoryFetcher to fetch in progress stories. It works only with Linear at the moment. Fetching Stories from Jira will be done in another PR.
A Personal API key has to be created and added to the opp config. The config for stories now looks like:
```
story:
tool: linear
url: https://full_url
token: linear_personal_api_key
```
> Use StoryFetcher

- cmd/pr.go
- cmd/pr_test.go
When creating a PR with a rebase (e.g. `opp pr -i` or `opp pr --base xxx`), the `--draft` flag doesn't work.
This is because the value of `--draft` was not taken from the previous Args when building the new Args.
This PR makes a deep copy of the args in order to make sure that the previous Args are taken into account.
> fix: --draft flag works when creating a PR with rebase

- cmd/clean.go
- go.mod
We need to take a closer look at how to delete multiple branches in parallel. In the mean time, we revert https://github.com/cupcicm/opp/pull/154.
> revert PR 154
